#Ray
latent_semantic_analysis: True

#Ray
LSA_Concepts: True

#Ray
kmeans: False

#Ray
tf_idf: False

#Gives a dictionary of words with their frequency
bag_of_words: True

#Gives a table of words with their frequency
#Only works when bag_of_words is True
word_frequency_table: True

#Gives a list of Named Entities
#Only works correctly when undergo no preprocessing
named_entities: False


# do T or F to turn on or off

