# notional (yaml) configuration file

# this specifies the data sources I'd like to use
data: 'books/'


# here's where I'll assign the preprocessing steps I'd like to execute 
preprocessing:
  complete_tokenize: True
  stem: True
  lemmatize: False
  stop_words: True
  lower_case: True
  punctuation: True
 

# now choose the algorithms!  functional: BOW 
algorithms:
  BOW: True
  LSA: False
  LDA: False
  Word2Vec: False  


visualization: 
  WordCloud: False
  FrequencyTable: True
