#Exports data to an excel doc in the same folder as scitext explorer
#Excel doc can be used with Tableau to create a word cloud
export_word_cloud: True

#Exports data to an excel doc in the same folder as scitext explorer
#Excel doc can be used with Tableau to create a word cloud
export_scatter_plot: True

#Ray
kmean_hist: True

#Ray
tsne: True

# do T or F to turn on or off